definitions:
  github_com_kiranraj27_sprint-planner_internal_domain.Card:
    description: Card entity containing value and set type.
    properties:
      id:
        type: integer
      set_type:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /cards:
    get:
      description: Fetch all cards with their values and set types
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_kiranraj27_sprint-planner_internal_domain.Card'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all cards
      tags:
      - Cards
swagger: "2.0"
